"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .meta import Meta, MetaTypedDict
from rapidapi_realtor_search_client.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AutocompleteTypedDict(TypedDict):
    pass


class Autocomplete(BaseModel):
    pass


class AutoCompleteResponseDataTypedDict(TypedDict):
    meta: NotRequired[MetaTypedDict]
    autocomplete: NotRequired[List[AutocompleteTypedDict]]


class AutoCompleteResponseData(BaseModel):
    meta: Optional[Meta] = None

    autocomplete: Optional[List[Autocomplete]] = None


class AutoCompleteResponseTypedDict(TypedDict):
    data: NotRequired[AutoCompleteResponseDataTypedDict]
    status: NotRequired[bool]
    message: NotRequired[str]


class AutoCompleteResponse(BaseModel):
    data: Optional[AutoCompleteResponseData] = None

    status: Optional[bool] = None

    message: Optional[str] = None
