"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from typing_extensions import NotRequired, TypedDict

from rapidapi_realtor_search_client.types import BaseModel


class AutoCompleteResponseMetaTypedDict(TypedDict):
    version: NotRequired[str]
    es_took: NotRequired[int]
    es_total_hits: NotRequired[int]


class AutoCompleteResponseMeta(BaseModel):
    version: Optional[str] = None

    es_took: Optional[int] = None

    es_total_hits: Optional[int] = None


class AutoCompleteResponseDataTypedDict(TypedDict):
    meta: NotRequired[AutoCompleteResponseMetaTypedDict]
    autocomplete: NotRequired[List[Dict[str, Any]]]


class AutoCompleteResponseData(BaseModel):
    meta: Optional[AutoCompleteResponseMeta] = None

    autocomplete: Optional[List[Dict[str, Any]]] = None


class AutoCompleteResponseTypedDict(TypedDict):
    data: NotRequired[AutoCompleteResponseDataTypedDict]
    status: NotRequired[bool]
    message: NotRequired[str]


class AutoCompleteResponse(BaseModel):
    data: Optional[AutoCompleteResponseData] = None

    status: Optional[bool] = None

    message: Optional[str] = None
