"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from rapidapi_realtor_search_client.types import BaseModel
from rapidapi_realtor_search_client.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AutoCompleteRequestTypedDict(TypedDict):
    input: str
    r"""States, cities, districts, addresses, zipcode.
    Example: New York

    """
    limit: NotRequired[int]
    r"""The number of items per response, for paging purpose.
    Example: 2

    """


class AutoCompleteRequest(BaseModel):
    input: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""States, cities, districts, addresses, zipcode.
    Example: New York

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""The number of items per response, for paging purpose.
    Example: 2

    """
