"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from rapidapi_realtor_search_client.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BoundaryTypedDict(TypedDict):
    type: NotRequired[str]
    coordinates: NotRequired[List[List[List[List[float]]]]]


class Boundary(BaseModel):
    type: Optional[str] = None

    coordinates: Optional[List[List[List[List[float]]]]] = None
