"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from rapidapi_realtor_search_client.types import BaseModel
from rapidapi_realtor_search_client.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPropertyDetailsRequestTypedDict(TypedDict):
    property_id: str
    r"""propertyId can be retrieved from /properties/search-buy or /properties/search-rent or /properties/search-sold or /properties/search-mls-id endpoint (data->results->property_id).
    Example: 4752427680

    """
    listing_id: NotRequired[str]
    r"""listingId can be retrieved from /properties/search-buy or /properties/search-rent or /properties/search-sold or /properties/search-mls-id endpoint (data->results->listing_id).
    Example: 2964420807

    """


class GetPropertyDetailsRequest(BaseModel):
    property_id: Annotated[
        str,
        pydantic.Field(alias="propertyId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""propertyId can be retrieved from /properties/search-buy or /properties/search-rent or /properties/search-sold or /properties/search-mls-id endpoint (data->results->property_id).
    Example: 4752427680

    """

    listing_id: Annotated[
        Optional[str],
        pydantic.Field(alias="listingId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""listingId can be retrieved from /properties/search-buy or /properties/search-rent or /properties/search-sold or /properties/search-mls-id endpoint (data->results->listing_id).
    Example: 2964420807

    """
