"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from rapidapi_realtor_search_client.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MetaTypedDict(TypedDict):
    current_page: NotRequired[int]
    limit: NotRequired[int]
    total_records: NotRequired[int]
    total_page: NotRequired[int]


class Meta(BaseModel):
    current_page: Annotated[Optional[int], pydantic.Field(alias="currentPage")] = None

    limit: Optional[int] = None

    total_records: Annotated[Optional[int], pydantic.Field(alias="totalRecords")] = None

    total_page: Annotated[Optional[int], pydantic.Field(alias="totalPage")] = None
