"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .boundary import Boundary, BoundaryTypedDict
from .meta import Meta, MetaTypedDict
from rapidapi_realtor_search_client.types import BaseModel
from typing import Any, List, Optional
from typing_extensions import NotRequired, TypedDict


class SearchPromotionTypedDict(TypedDict):
    name: NotRequired[str]
    slots: NotRequired[List[Any]]
    promoted_properties: NotRequired[List[List[Any]]]


class SearchPromotion(BaseModel):
    name: Optional[str] = None

    slots: Optional[List[Any]] = None

    promoted_properties: Optional[List[List[Any]]] = None


class ResultsTypedDict(TypedDict):
    pass


class Results(BaseModel):
    pass


class DataTypedDict(TypedDict):
    count: NotRequired[int]
    total: NotRequired[int]
    boundary: NotRequired[BoundaryTypedDict]
    search_promotion: NotRequired[SearchPromotionTypedDict]
    results: NotRequired[List[ResultsTypedDict]]


class Data(BaseModel):
    count: Optional[int] = None

    total: Optional[int] = None

    boundary: Optional[Boundary] = None

    search_promotion: Optional[SearchPromotion] = None

    results: Optional[List[Results]] = None


class SearchBuyResponseTypedDict(TypedDict):
    data: NotRequired[DataTypedDict]
    meta: NotRequired[MetaTypedDict]
    status: NotRequired[bool]
    message: NotRequired[str]


class SearchBuyResponse(BaseModel):
    data: Optional[Data] = None

    meta: Optional[Meta] = None

    status: Optional[bool] = None

    message: Optional[str] = None
