"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SortBySold(str, Enum):
    LOWEST_PRICE = "lowest_price"
    HIGHEST_PRICE = "highest_price"
