"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SortBy(str, Enum):
    RELEVANCE = "relevance"
    NEWEST = "newest"
    LOWEST_PRICE = "lowest_price"
    HIGHEST_PRICE = "highest_price"
    OPEN_HOUSE_DATE = "open_house_date"
    PRICE_REDUCED = "price_reduced"
    LARGEST_SQUAREFOOT = "largest_squarefoot"
    PHOTO_COUNT = "photo_count"
