"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "rapidapi-realtor-search-client"
__version__: str = "0.2.1"
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.547.2"
__user_agent__: str = (
    "speakeasy-sdk/python 0.2.1 2.547.2 1.0.0 rapidapi-realtor-search-client"
)

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
